### ISSUE TITLE
Supervisor stats put call nil

### ISSUE THREAD

**Issue by RobinUS2** [RobinUS2/cloudpelican-lsd#11]
```
2015/07/02 05:45:33 Failed json umarshal unexpected end of JSON input
2015/07/02 05:45:33 http: panic serving 176.58.112.90:43478: runtime error: invalid memory address or nil pointer dereference
goroutine 521373 [running]:
net/http.func·011()
        /usr/lib/golang/src/net/http/server.go:1130 +0xbb
main.(*FilterManager).GetFilter(0xc20802c960, 0xc20942e982, 0x24, 0x40)
        /root/cloudpelican-lsd/supervisor/filter_manager.go:366 +0x27a
main.PutStatsFilters(0x7f16e8d0b510, 0xc2096940a0, 0xc208a1b2b0, 0x0, 0x0, 0x0)
        /root/cloudpelican-lsd/supervisor/supervisor.go:496 +0xb46
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc20803b200, 0x7f16e8d0b510, 0xc2096940a0, 0xc208a1b2b0)
        /root/cloudpelican-lsd/supervisor/src/github.com/julienschmidt/httprouter/router.go:299 +0x18e
net/http.serverHandler.ServeHTTP(0xc20805a0c0, 0x7f16e8d0b510, 0xc2096940a0, 0xc208a1b2b0)
        /usr/lib/golang/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc209694460)
        /usr/lib/golang/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:1751 +0x35e
```

**Comment by RobinUS2** [comment]
Solved.
