### ISSUE TITLE
NPE select 

### ISSUE THREAD

**Issue by RobinUS2** [RobinUS2/cloudpelican-lsd#20]
$ cloudpelican 
cloudpelican> select \* from stream:default as 's00'
cloudpelican> 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x13028]

goroutine 27 [running]:
runtime.panic(0x2e8b40, 0x4d1e84)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.func·001()
    /Users/robin/Documents/cloudpelican-lsd/cli/cloudpelican-lsd.go:551 +0xf78
created by main.executeSelect
    /Users/robin/Documents/cloudpelican-lsd/cli/cloudpelican-lsd.go:623 +0x957

**Comment by RobinUS2** [comment]
Fixed.
